language: php

php:
  - 5.4
  - 5.5

before_script:
  # starting PHP server (PHP 5.4)
  - php -S 127.0.0.1:4000 &
  - sleep 3

  # installing wp-cli
  - curl https://raw.github.com/wp-cli/wp-cli.github.com/master/installer.sh | bash

  # setting up
  - sh setup.sh

script: "php codecept.phar run --steps"