language: php

php:
  - 5.4
  - 5.5

before_script:
  - php -S localhost:4000 &
  - curl https://raw.github.com/wp-cli/wp-cli.github.com/master/installer.sh | bash
  - sh $HOME/.wp-cli/bin/wp db create
  - sh $HOME/.wp-cli/bin/wp core install --title="UnTestEd" --admin_password="admin" --url="http://untested.com"

script: "php codecept.phar run"